r"""NaTIS vehicle licence-disc decoding and parsing.

Programme phase 1 (feature A / A1) of the 2026-09-23 ABI programme.

Two jobs live here:

1. **image -> barcode payload(s)** — :func:`decode_disc_image`. The NaTIS vehicle licence
   disc barcode is a plain-text PDF417 (master plan decision D1: *not* RSA-encrypted, unlike
   a driver's licence card). Decoding is server-side so there is one code path for camera,
   file upload and paste; the engine choice is measured, not assumed — see
   ``docs/plans/disc-decode-findings.md``.
2. **payload text -> fields** — :func:`parse_disc_text`, a **faithful Python port of the
   already-shipping TrailerPro parser**
   (``/mnt/d/Claude/trailer-rental-app/src/lib/saDiscParser.ts``, 379 lines). Do not invent a
   second grammar: the port is asserted field-by-field against the real TypeScript output in
   ``tests/test_programme_20260923_vehicle_disk.py`` (fixtures regenerated by
   ``scripts/disc_parity_ts.mts``).

Deliberate differences from the reference, all documented, all additive:

* ``tare_kg`` / ``gvm_kg`` come back as ``float | None`` instead of the reference's strings,
  because the ``vehicles`` table stores REAL columns and a missing mass must be NULL, never 0.
* The label-value mass patterns require the number to *end* (``(\d{3,5})(?!\d)``) and the result
  is range-guarded to 300-80000 kg. Measured reference behaviour: ``GVM 1234567`` yields
  ``12345`` there because the regex takes the first five digits and checks nothing. D3 is "never
  invent a vehicle figure", so these guards only ever blank a nonsense value — they cannot
  produce one, and every well-formed disc is unaffected.
* ``registering_authority``, ``control_number`` and ``registration_number`` are surfaced. The
  reference already parses the first two into locals and the third as ``registerNumber``, but
  never exposes them; A1's spec asks for them.
* ``unparsed_fields`` (tokens carrying no signal the parser recognises — no label keyword, no
  number, no date, no known make/colour/type, no text that landed in a field) and ``raw_text``
  are returned so staff can eyeball anything that was not recognised before saving.

Known reference behaviour carried over unchanged (measured, see the findings doc): the
percent-delimited branch can assign the NaTIS registration number to ``engine_number`` when
that field appears before the engine number, and the documented "fixed-width positional"
layout is **not** actually parsed — a space-separated payload only yields plate/VIN/engine
through the top-level regexes. Both are recorded for Don rather than silently "fixed".

There is **no towing capacity and no GCM on a licence disk** (D3) — this module never
produces one.
"""

from __future__ import annotations

import io
import re
from datetime import datetime
from typing import Any, Callable, Iterable, Mapping, Sequence

__all__ = [
    "DISC_FIELD_KEYS",
    "DEFAULT_ENGINE_ORDER",
    "DiscDecodeError",
    "DiscErrorKind",
    "FIELD_LABELS",
    "decode_and_parse",
    "decode_disc_image",
    "decode_payloads",
    "parse_disc_text",
    "is_disc_parseable",
]


# ── Errors ──────────────────────────────────────────────────────────────────


class DiscErrorKind:
    """Distinct failure kinds — the scan UI must tell these apart (A1 spec step 4)."""

    NO_BARCODE = "no_barcode"
    """Nothing decoded: no PDF417 found in any image variant (or no engine installed)."""

    UNPARSEABLE = "unparseable"
    """A barcode decoded, but the payload yielded no recognisable disc field."""

    IMAGE_UNREADABLE = "image_unreadable"
    """The bytes were not a readable image."""


class DiscDecodeError(Exception):
    """Raised when a disc image cannot be turned into fields.

    ``kind`` is one of :class:`DiscErrorKind` so callers can show the right message: "we could
    not find a barcode on that photo — try again flatter/closer" reads very differently from
    "we found the barcode but could not read the fields off it".
    """

    def __init__(self, kind: str, message: str = "", *, detail: str = ""):
        super().__init__(message or kind)
        self.kind = kind
        self.detail = detail

    def __str__(self) -> str:  # pragma: no cover - trivial
        return f"{self.kind}: {super().__str__()}"


# ── Field vocabulary ────────────────────────────────────────────────────────

#: The fields :func:`parse_disc_text` can produce. Everything a NaTIS disc actually carries
#: (D1/D3) — no towing capacity, no GCM.
DISC_FIELD_KEYS: tuple[str, ...] = (
    "licence_number",
    "registering_authority",
    "control_number",
    "registration_number",
    "make",
    "model",
    "colour",
    "vin",
    "engine_number",
    "expiry_date",
    "tare_kg",
    "gvm_kg",
    "vehicle_type",
)

FIELD_LABELS: Mapping[str, str] = {
    "licence_number": "Licence number (number plate)",
    "registering_authority": "Registering authority",
    "control_number": "Control number",
    "registration_number": "Vehicle registration number (NaTIS ref)",
    "make": "Make",
    "model": "Model / description",
    "colour": "Colour",
    "vin": "VIN",
    "engine_number": "Engine number",
    "expiry_date": "Licence expiry date",
    "tare_kg": "Tare (kg)",
    "gvm_kg": "GVM (kg)",
    "vehicle_type": "Vehicle category",
}


# ── Patterns (mirrors saDiscParser.ts:35-74) ────────────────────────────────

# re.ASCII everywhere: the reference is a JavaScript regex engine, whose \b, \d, \s and [A-Z]
# are ASCII-only. Matching JavaScript exactly matters more here than Unicode friendliness.
VIN_RE = re.compile(r"\b([A-HJ-NPR-Z0-9]{17})\b", re.ASCII)
PLATE_RE = re.compile(
    r"\b([A-Z]{2,3}[\s-]?\d{1,6}[\s-]?[A-Z]{0,3}(?:\s?[A-Z]{2})?)\b", re.ASCII
)

_ISO_COMPACT_RE = re.compile(r"^(\d{4})(\d{2})(\d{2})$", re.ASCII)
_ISO_DASHED_RE = re.compile(r"^(\d{4})[/\-.](\d{2})[/\-.](\d{2})$", re.ASCII)
_LOCAL_DASHED_RE = re.compile(r"^(\d{2})[/\-.](\d{2})[/\-.](\d{4})$", re.ASCII)
_LOOSE_DATE_RE = re.compile(r"(\d{4})(\d{2})(\d{2})", re.ASCII)

DATE_FORMATS: tuple[tuple[re.Pattern[str], Callable[[re.Match[str]], str]], ...] = (
    (_ISO_COMPACT_RE, lambda m: f"{m.group(1)}-{m.group(2)}-{m.group(3)}"),
    (_ISO_DASHED_RE, lambda m: f"{m.group(1)}-{m.group(2)}-{m.group(3)}"),
    (_LOCAL_DASHED_RE, lambda m: f"{m.group(3)}-{m.group(2)}-{m.group(1)}"),
)

KNOWN_MAKES = frozenset(
    {
        "TOYOTA", "VOLKSWAGEN", "VW", "FORD", "CHEVROLET", "CHEV", "NISSAN", "BMW",
        "MERCEDES", "MERCEDES-BENZ", "MERCEDES BENZ", "MB", "HYUNDAI", "KIA", "MAZDA",
        "HONDA", "ISUZU", "MITSUBISHI", "OPEL", "RENAULT", "PEUGEOT", "TATA", "MAHINDRA",
        "JEEP", "LAND ROVER", "LANDROVER", "RANGE ROVER", "VOLVO", "SCANIA", "MAN",
        "HINO", "DAIHATSU", "SUZUKI", "FIAT", "ALFA ROMEO", "ALFA", "DODGE", "RAM",
        "FREIGHTLINER", "AUDI", "SUBARU", "CITROEN", "SEAT", "SKODA", "LEXUS",
        "INFINITI", "PORSCHE", "FERRARI", "LAMBORGHINI", "INTERNATIONAL", "KENWORTH",
        "PETERBILT", "WESTERN STAR", "UD", "YUTONG", "POWERSTAR", "HENRED", "AFRIT",
        "SA TRAILER", "SERCO", "GWM", "HAVAL", "CHERY", "JAC", "BAIC", "FOTON",
        "IVECO", "MINI", "SMART",
    }
)

KNOWN_COLOURS = frozenset(
    {
        "WHITE", "BLACK", "SILVER", "GREY", "GRAY", "RED", "BLUE", "GREEN", "YELLOW",
        "ORANGE", "BROWN", "GOLD", "BEIGE", "MAROON", "PURPLE", "PINK", "CREAM",
        "BRONZE", "CHARCOAL", "NAVY", "DARK BLUE", "LIGHT BLUE", "DARK GREY",
        "LIGHT GREY", "PEARL", "CHAMPAGNE", "GUNMETAL", "LIME", "TURQUOISE",
        "WINE", "BURGUNDY", "TAN", "COPPER", "IVORY",
    }
)

# Ordered, not a set: the reference iterates its Set in insertion order in
# findVehicleType's "does the raw text contain any of these" pass, so a payload containing
# both "MOTOR CAR" and "TRAILER" resolves to "MOTOR CAR". Preserve that order.
VEHICLE_TYPES: tuple[str, ...] = (
    "MOTOR CAR", "MOTORCAR", "LDV", "LIGHT DELIVERY VEHICLE", "MINIBUS",
    "BUS", "TRUCK", "MOTORCYCLE", "MOTOR CYCLE", "TRAILER", "CARAVAN",
    "SEMI-TRAILER", "SPECIAL VEHICLE", "STATION WAGON",
)

_MIN_MASS_KG = 300
_MAX_MASS_KG = 80000

#: Spaces are deliberately NOT separators — the reference splits on newlines, pipes,
#: semicolons, percents and tabs only. A space-separated payload therefore arrives as a single
#: token (measured: see the findings doc, "fixed-width" fixture).
TOKEN_SPLIT_RE = re.compile(r"[\n\r|;%\t]+", re.ASCII)
_MASS_TOKEN_RE = re.compile(r"^(\d{3,5})(\s*kg)?$", re.ASCII | re.IGNORECASE)
_PLAIN_MASS_RE = re.compile(r"^\d{3,5}$", re.ASCII)
_ENGINE_TOKEN_RE = re.compile(r"^[A-Z0-9]{6,15}$", re.ASCII)
_HAS_LETTER_RE = re.compile(r"[A-Z]", re.ASCII)
_HAS_DIGIT_RE = re.compile(r"\d", re.ASCII)
_ALNUM6_15_RE = re.compile(r"^[A-Z0-9]{6,15}$", re.ASCII)


# ── Helpers (mirrors saDiscParser.ts:78-166) ────────────────────────────────


def normalise_date(value: str) -> str:
    """``20270331`` / ``2027-03-31`` / ``31/03/2027`` -> ``2027-03-31``; else ``''``."""
    text = (value or "").strip()
    for pattern, fmt in DATE_FORMATS:
        match = pattern.match(text)
        if match:
            return fmt(match)
    return ""


def is_plausible_date(iso: str, *, now_year: int | None = None) -> bool:
    """The reference guards against mis-reading numbers as dates: year within now-5..now+15
    and a real month."""
    if not iso or len(iso) < 7:
        return False
    try:
        year = int(iso[0:4])
        month = int(iso[5:7])
    except ValueError:
        return False
    current = now_year if now_year is not None else datetime.now().year
    return (current - 5) <= year <= (current + 15) and 1 <= month <= 12


def find_date(tokens: Sequence[str], *, now_year: int | None = None) -> str:
    """Any plausible date in the tokens; the **latest** one wins (issue vs expiry)."""
    dates: list[str] = []
    for token in tokens:
        parsed = normalise_date(token)
        if parsed and is_plausible_date(parsed, now_year=now_year):
            dates.append(parsed)
    for token in tokens:
        match = _LOOSE_DATE_RE.search(token)
        if match:
            candidate = f"{match.group(1)}-{match.group(2)}-{match.group(3)}"
            if is_plausible_date(candidate, now_year=now_year) and candidate not in dates:
                dates.append(candidate)
    if dates:
        return sorted(dates)[-1]
    return ""


def find_make(tokens: Sequence[str]) -> tuple[str, int]:
    """First known make in the tokens, or a two-token compound (``LAND ROVER``)."""
    for index, token in enumerate(tokens):
        upper = token.upper().strip()
        if upper in KNOWN_MAKES:
            return upper, index
        if index + 1 < len(tokens):
            compound = f"{upper} {tokens[index + 1].upper().strip()}"
            if compound in KNOWN_MAKES:
                return compound, index
    return "", -1


def find_colour(tokens: Sequence[str]) -> str:
    for token in tokens:
        upper = token.upper().strip()
        if upper in KNOWN_COLOURS:
            return upper
    return ""


def find_vehicle_type(tokens: Sequence[str]) -> str:
    for token in tokens:
        upper = token.upper().strip()
        if upper in VEHICLE_TYPES:
            return upper
    raw = " ".join(tokens).upper()
    for vehicle_type in VEHICLE_TYPES:
        if vehicle_type in raw:
            return vehicle_type
    return ""


def find_masses(tokens: Sequence[str]) -> tuple[str, str]:
    """``(gross, tare)`` — the reference assumes the heaviest number is the GVM."""
    masses: list[int] = []
    for token in tokens:
        match = _MASS_TOKEN_RE.match(token.strip())
        if match:
            value = int(match.group(1))
            if _MIN_MASS_KG <= value <= _MAX_MASS_KG:
                masses.append(value)
    masses.sort(reverse=True)
    gross = str(masses[0]) if len(masses) > 0 else ""
    tare = str(masses[1]) if len(masses) > 1 else ""
    return gross, tare


def is_vin(value: str) -> bool:
    return bool(VIN_RE.search(value.strip()))


# ── Real modern disc layout (measured, positional) ──────────────────────────

#: The 2026 sample disc decodes to a `%`-delimited record whose field ORDER carries the meaning —
#: there are no labels and no `|`/newline separators to sniff, so the heuristic passes below
#: cannot be trusted to place every field. Measured on the real payload:
#:   %MVL1CC53%0148%4522A001%1%4024048GB8LY%KP35XKGP%SHS812W%Station wagon / Stasiewa%
#:   MITSUBISHI%ASX%White / Wit%JMYXTGA2WDZ000956%4B11LC0187%2027-07-31%
#: split('%') -> [ '', 'MVL1CC53', '0148', '4522A001', '1', then the fields below ]
#: Only the unambiguous fields are taken here. The three identifier fields (5/6/7) are left to
#: the generic pass plus review: which of them is the NaTIS registration number and which the
#: licence number (plate) has NOT been confirmed against a full printed disc face, and D3 forbids
#: guessing. `MVL1CC53` (the form identifier) is likewise not a vehicle figure.
POSITIONAL_FORM_PREFIX = "%MVL"
_POSITIONAL_MIN_FIELDS = 16
POSITIONAL_TYPE_INDEX = 8
POSITIONAL_MAKE_INDEX = 9
POSITIONAL_MODEL_INDEX = 10
POSITIONAL_COLOUR_INDEX = 11
POSITIONAL_VIN_INDEX = 12
POSITIONAL_ENGINE_INDEX = 13
POSITIONAL_EXPIRY_INDEX = 14
POSITIONAL_IDENTIFIER_INDEXES = (5, 6, 7)


def _first_dual_language_part(value: str) -> str:
    """``"Station wagon / Stasiewa"`` -> ``"Station wagon"`` (the disc prints EN / AF)."""
    return value.split("/")[0].strip()


def parse_natis_positional(raw: str) -> dict[str, str] | None:
    """Parse the modern positional NaTIS layout, or ``None`` if this is not that layout.

    The record is self-describing in one useful way — field 2 is its own length:

        %MVL1CC53%0148%...    ->  0148 == len(payload) == 148

    That self-check is what makes it safe to treat the layout as positional at all, and it is the
    first thing a piece of corrupt data fails. Three driver's-licence samples and every older
    "label-value" / delimited disc keep working through the heuristic passes below.
    """
    if not raw.startswith(POSITIONAL_FORM_PREFIX):
        return None
    fields = raw.split("%")
    if len(fields) < _POSITIONAL_MIN_FIELDS:
        return None

    declared_length = fields[2]
    if not declared_length.isdigit() or int(declared_length) != len(raw.strip()):
        return None

    vin = fields[POSITIONAL_VIN_INDEX].strip().upper()
    if not re.fullmatch(r"[A-HJ-NPR-Z0-9]{17}", vin, re.ASCII):
        return None

    expiry = normalise_date(fields[POSITIONAL_EXPIRY_INDEX])
    if not expiry:
        return None

    result = {
        "vehicleType": _first_dual_language_part(fields[POSITIONAL_TYPE_INDEX]).upper(),
        "make": fields[POSITIONAL_MAKE_INDEX].strip().upper(),
        "model": fields[POSITIONAL_MODEL_INDEX].strip(),
        "colour": _first_dual_language_part(fields[POSITIONAL_COLOUR_INDEX]).upper(),
        "vin": vin,
        "engineNumber": fields[POSITIONAL_ENGINE_INDEX].strip().upper(),
        "expiryDate": expiry,
        "positionalIdentifiers": [
            fields[index].strip() for index in POSITIONAL_IDENTIFIER_INDEXES if fields[index].strip()
        ],
    }
    return result


# ── Label-value parsing (mirrors saDiscParser.ts:184-231) ────────────────────

# The reference's own precedence: label-value > percent-delimited > token.
_LABEL_PATTERNS: tuple[tuple[str, re.Pattern[str]], ...] = tuple(
    (key, re.compile(pattern, re.ASCII | re.IGNORECASE | re.MULTILINE))
    for key, pattern in (
        ("licenceNumber", r"licence\s*(?:number|no)[:\s=]+([^\n\r|;%]+)"),
        ("licenceNumber", r"license\s*(?:number|no)[:\s=]+([^\n\r|;%]+)"),
        ("licenceNumber", r"number\s*plate[:\s=]+([^\n\r|;%]+)"),
        ("registerNumber", r"vehicle\s*register\s*(?:number|no)[:\s=]+([^\n\r|;%]+)"),
        ("registerNumber", r"reg(?:istration)?\s*(?:number|no|#)[:\s=]+([^\n\r|;%]+)"),
        ("make", r"\bmake[:\s=]+([^\n\r|;%]+)"),
        ("model", r"series\s*(?:name)?[:\s=]+([^\n\r|;%]+)"),
        ("model", r"model[:\s=]+([^\n\r|;%]+)"),
        ("model", r"vehicle\s*description[:\s=]+([^\n\r|;%]+)"),
        ("model", r"description[:\s=]+([^\n\r|;%]+)"),
        (
            "vin",
            r"(?:vehicle\s*identification\s*number|VIN)\s*(?:\(VIN\))?\s*[:\s=]+\s*"
            r"([A-HJ-NPR-Z0-9]{17})",
        ),
        ("vin", r"VIN[:\s=]+([A-HJ-NPR-Z0-9]{17})"),
        ("engineNumber", r"engine\s*(?:number|no|#)[:\s=]+([A-Z0-9][^\n\r|;%]*)"),
        ("expiryDate", r"date\s*of\s*expiry[:\s=]+([^\n\r|;%]+)"),
        ("expiryDate", r"expiry\s*(?:date)?[:\s=]+([^\n\r|;%]+)"),
        ("expiryDate", r"licence\s*expiry[:\s=]+([^\n\r|;%]+)"),
        ("tare", r"tare[^:\n\r]*?[:\s=]+\s*(\d{3,5})(?!\d)"),
        ("grossMass", r"(?:GVM|gross\s*(?:vehicle\s*)?mass)[^:\n\r]*?[:\s=]+\s*(\d{3,5})(?!\d)"),
        ("colour", r"colou?r[:\s=]+([^\n\r|;%]+)"),
        ("vehicleType", r"vehicle\s*category[:\s=]+([^\n\r|;%]+)"),
        ("vehicleType", r"vehicle\s*type[:\s=]+([^\n\r|;%]+)"),
        # ── ABI extensions (new keys only — none of these can move a reference field) ──
        ("registeringAuthority", r"registering\s*authority[:\s=]+([^\n\r|;%]+)"),
        ("registeringAuthority", r"register\s*authority[:\s=]+([^\n\r|;%]+)"),
        ("controlNumber", r"control\s*(?:number|no)[:\s=]+([^\n\r|;%]+)"),
    )
)

_LABEL_DEFAULTS: Mapping[str, str] = {
    "licenceNumber": "",
    "registerNumber": "",
    "registeringAuthority": "",
    "controlNumber": "",
    "make": "",
    "model": "",
    "vin": "",
    "engineNumber": "",
    "expiryDate": "",
    "tare": "",
    "grossMass": "",
    "colour": "",
    "vehicleType": "",
}


def parse_labelled_fields(raw: str) -> dict[str, str]:
    result = dict(_LABEL_DEFAULTS)
    for key, pattern in _LABEL_PATTERNS:
        if result[key]:
            continue
        match = pattern.search(raw)
        if match:
            value = match.group(1).strip()
            if key == "expiryDate":
                value = normalise_date(value) or value
            if value:
                result[key] = value
    if not result["licenceNumber"] and result["registerNumber"]:
        result["licenceNumber"] = result["registerNumber"]
    return result


# ── Percent-delimited parsing (mirrors saDiscParser.ts:235-273) ─────────────


def parse_percent_delimited(raw: str) -> dict[str, str] | None:
    if "%" not in raw:
        return None
    fields = [part.strip() for part in raw.split("%")]
    if len(fields) < 8:
        return None

    result: dict[str, str] = {}
    for field in fields:
        if not field:
            continue
        if VIN_RE.search(field) and not result.get("vin"):
            result["vin"] = VIN_RE.search(field).group(1)  # type: ignore[union-attr]
            continue
        if PLATE_RE.search(field) and not result.get("licenceNumber"):
            result["licenceNumber"] = field
            continue
        if field.upper() in KNOWN_MAKES and not result.get("make"):
            result["make"] = field.upper()
            continue
        if field.upper() in KNOWN_COLOURS and not result.get("colour"):
            result["colour"] = field.upper()
            continue
        parsed_date = normalise_date(field)
        if parsed_date and is_plausible_date(parsed_date):
            existing = result.get("expiryDate")
            if not existing or parsed_date > existing:
                result["expiryDate"] = parsed_date
            continue
        if _PLAIN_MASS_RE.match(field):
            value = int(field)
            if _MIN_MASS_KG <= value <= _MAX_MASS_KG:
                if not result.get("tare"):
                    result["tare"] = field
                    continue
                if not result.get("grossMass"):
                    result["grossMass"] = field
                    continue
        if (
            _ALNUM6_15_RE.match(field)
            and _HAS_LETTER_RE.search(field)
            and _HAS_DIGIT_RE.search(field)
            and not is_vin(field)
            and not result.get("engineNumber")
        ):
            result["engineNumber"] = field

    return result if any(result.values()) else None


# ── Main entry (mirrors saDiscParser.ts:277-379) ────────────────────────────


def _token_list(raw: str) -> list[str]:
    return [token.strip() for token in TOKEN_SPLIT_RE.split(raw) if token.strip()]


# A token is "recognised" when it carries some signal the parser understands: a label keyword,
# a date, a number, a known make/colour/type, or text that ended up in a parsed field. Tokens
# with none of that are surfaced in ``unparsed_fields`` so staff can eyeball them. Purely
# cosmetic — it never feeds a parsed field, so it cannot shift parity with the reference.
_RECOGNISED_HINT_RE = re.compile(
    r"licence|license|lisensie|number\s*plate|plate|register|control|make|model|series|"
    r"description|vin|identification|engine|expir|tare|gvm|mass|colou?r|category|type|date",
    re.ASCII | re.IGNORECASE,
)
_ANY_DATE_RE = re.compile(
    r"\d{4}[/\-.]\d{2}[/\-.]\d{2}|\d{2}[/\-.]\d{2}[/\-.]\d{4}|\d{8}", re.ASCII
)
_CONTAINMENT_KEYS = (
    "vin",
    "engine_number",
    "licence_number",
    "make",
    "model",
    "colour",
    "vehicle_type",
    "registering_authority",
    "control_number",
    "registration_number",
)


def _token_is_recognised(token: str, parsed: Mapping[str, Any]) -> bool:
    stripped = token.strip()
    if not stripped:
        return True
    upper = stripped.upper()
    if upper in KNOWN_MAKES or upper in KNOWN_COLOURS or upper in VEHICLE_TYPES:
        return True
    if _RECOGNISED_HINT_RE.search(stripped):
        return True
    if _ANY_DATE_RE.search(stripped) or _HAS_DIGIT_RE.search(stripped):
        return True
    for key in _CONTAINMENT_KEYS:
        value = str(parsed.get(key) or "").strip()
        if len(value) >= 3 and value.upper() in upper:
            return True
    return False


def _explained_token_indexes(
    tokens: Sequence[str], raw: str, parsed: Mapping[str, Any]
) -> set[int]:
    return {index for index, token in enumerate(tokens) if _token_is_recognised(token, parsed)}


def _mass_to_float(value: str) -> float | None:
    """Blank -> ``None`` (never 0), and out-of-range -> ``None``.

    ABI safety guard, the one place this module is stricter than the reference: the reference's
    *label-value* mass regexes accept any 3-5 digit run with no range check, so a garbage
    payload can yield a nonsense figure (measured: ``GVM 1234567`` -> ``12345``). Decision D3 is
    "never invent a vehicle figure", so anything outside the physical 300-80000 kg window is
    dropped instead of stored. This can only ever blank a value, never produce one.
    """
    try:
        number = float(str(value).strip())
    except (TypeError, ValueError):
        return None
    if not (_MIN_MASS_KG <= number <= _MAX_MASS_KG):
        return None
    return number


def parse_disc_text(raw: str) -> dict[str, Any]:
    """Parse a decoded disc payload into ABI's field names.

    Never raises: junk in gives empty fields, ``confidence == 'low'`` and the verbatim text
    back, so the scan screen can always fall back to manual entry.
    """
    raw = raw or ""

    # ── Phase 0: the modern positional layout, when the record proves it is one ──
    positional = parse_natis_positional(raw) or {}

    # ── Phase 1: label-value, then percent-delimited ──
    labelled = parse_labelled_fields(raw)
    percent = parse_percent_delimited(raw) or {}

    # ── Phase 2: token pattern matching ──
    tokens = _token_list(raw)

    vin_match = VIN_RE.search(raw)
    plate_match = PLATE_RE.search(raw)
    token_make, make_index = find_make(tokens)
    token_colour = find_colour(tokens)
    token_vehicle_type = find_vehicle_type(tokens)
    token_expiry_date = find_date(tokens)
    gross_mass_token, tare_token = find_masses(tokens)

    token_model = ""
    if token_make and make_index >= 0 and make_index + 1 < len(tokens):
        following = tokens[make_index + 1].strip()
        if (
            following.upper() not in KNOWN_COLOURS
            and following.upper() not in VEHICLE_TYPES
            and not VIN_RE.search(following)
            and not normalise_date(following)
        ):
            token_model = following

    token_engine_number = ""
    if vin_match:
        vin_index = raw.find(vin_match.group(1))
        after_vin = raw[vin_index + 17 : vin_index + 50].strip()
        engine_match = re.match(r"[\s|;%\n\r]*([A-Z0-9]{5,15})", after_vin, re.ASCII)
        if engine_match:
            token_engine_number = engine_match.group(1)
    if not token_engine_number:
        for token in tokens:
            trimmed = token.strip()
            if (
                _ENGINE_TOKEN_RE.match(trimmed)
                and _HAS_LETTER_RE.search(trimmed)
                and _HAS_DIGIT_RE.search(trimmed)
                and not is_vin(trimmed)
                and not PLATE_RE.search(trimmed)
                and trimmed not in KNOWN_MAKES
                and trimmed not in KNOWN_COLOURS
            ):
                token_engine_number = trimmed
                break

    token_vin = vin_match.group(1) if vin_match else ""
    token_plate = re.sub(r"\s+", " ", plate_match.group(1)).strip() if plate_match else ""

    # ── Phase 3: merge — positional > label-value > percent > token ──
    vin = positional.get("vin") or labelled["vin"] or percent.get("vin") or token_vin
    plate = labelled["licenceNumber"] or percent.get("licenceNumber") or token_plate
    make = positional.get("make") or labelled["make"] or percent.get("make") or token_make
    model = positional.get("model") or labelled["model"] or percent.get("model") or token_model
    engine_number = (
        positional.get("engineNumber")
        or labelled["engineNumber"]
        or percent.get("engineNumber")
        or token_engine_number
    )
    expiry_candidates = [
        candidate
        for candidate in (
            positional.get("expiryDate"),
            labelled["expiryDate"],
            percent.get("expiryDate"),
            token_expiry_date,
        )
        if candidate
    ]
    expiry_date = max(expiry_candidates) if expiry_candidates else ""
    tare = labelled["tare"] or percent.get("tare") or tare_token
    gvm = labelled["grossMass"] or percent.get("grossMass") or gross_mass_token
    colour = (
        positional.get("colour") or labelled["colour"] or percent.get("colour") or token_colour
    )
    vehicle_type = positional.get("vehicleType") or labelled["vehicleType"] or token_vehicle_type

    confidence = "high" if (vin and plate and (make or expiry_date)) else "low"

    parsed: dict[str, Any] = {
        "licence_number": plate,
        "registering_authority": labelled["registeringAuthority"],
        "control_number": labelled["controlNumber"],
        "registration_number": labelled["registerNumber"],
        "make": make,
        "model": model,
        "colour": colour,
        "vin": vin,
        "engine_number": engine_number,
        "expiry_date": expiry_date,
        "tare_kg": _mass_to_float(tare),
        "gvm_kg": _mass_to_float(gvm),
        "vehicle_type": vehicle_type,
        "confidence": confidence,
        "raw_text": raw,
    }

    explained = _explained_token_indexes(tokens, raw, parsed)
    unparsed: dict[str, str] = {
        token: "unrecognised"
        for index, token in enumerate(tokens)
        if index not in explained
    }
    for identifier in positional.get("positionalIdentifiers", []):
        used = {plate.strip().upper(), (labelled["registerNumber"] or "").strip().upper()}
        if identifier.strip().upper() in used:
            continue  # this one is accounted for: it is the plate/registration we kept
        unparsed[identifier] = (
            "unassigned disc identifier — which of these fields is the NaTIS registration "
            "number and which is the licence number still needs the printed disc face"
        )
    parsed["unparsed_fields"] = unparsed
    return parsed


def is_disc_parseable(parsed: Mapping[str, Any]) -> bool:
    """True when at least one real disc field came out of a payload."""
    return any(str(parsed.get(key) or "").strip() for key in DISC_FIELD_KEYS)


# ── Engine layer ────────────────────────────────────────────────────────────

#: Measured default (see docs/plans/disc-decode-findings.md): on the REAL disc photograph both
#: engines decode on the *original* variant, and zxing-cpp does it in 22 ms from a 2 MB wheel
#: while pdf417decoder needs 251 ms and drags in numpy + opencv-python (~115 MB installed).
#: zxing-cpp missed only two driver's-licence-card samples, which are not ABI's use case. So
#: zxing-cpp is primary; pdf417decoder stays supported as an optional second opinion (the code
#: skips an engine that is not installed, and requirements.txt does not ship it).
DEFAULT_ENGINE_ORDER: tuple[str, ...] = ("zxing-cpp", "pdf417decoder")


def _engine_zxing_cpp(image: Any) -> list[str]:
    import zxingcpp  # imported lazily: a missing engine must not break app import

    results = zxingcpp.read_barcodes(image, formats=zxingcpp.BarcodeFormat.PDF417)
    return [result.text for result in results if getattr(result, "text", "")]


def _engine_pdf417decoder(image: Any) -> list[str]:
    from pdf417decoder import PDF417Decoder  # type: ignore[import-not-found]

    decoder = PDF417Decoder(image.convert("RGB"))
    decoder.decode()
    payloads: list[str] = []
    for payload in getattr(decoder, "barcodes_data", None) or []:
        raw = bytes(payload)
        # Disc payloads are plain text; a binary payload here means a driver's licence card,
        # which is a different (RSA) path this module deliberately does not handle.
        payloads.append(raw.decode("utf-8", "replace"))
    return payloads


_ENGINES: Mapping[str, Callable[[Any], list[str]]] = {
    "zxing-cpp": _engine_zxing_cpp,
    "pdf417decoder": _engine_pdf417decoder,
}

#: Variant ladder — the plan's minimum (original, grayscale, contrast, 2x, top crop, rotate 90)
#: plus the extra attempts the proven archive decoder needed on glare-heavy phone photos.
VARIANT_NAMES: tuple[str, ...] = (
    "original",
    "grayscale",
    "contrast-1.8",
    "contrast-2.5",
    "upscale-150",
    "upscale-2x",
    "upscale-3x-gray-contrast",
    "topcrop-40",
    "middlecrop-70",
    "rotate90",
    "rotate270",
)


def image_variants(image: Any) -> list[tuple[str, Any]]:
    """Decode attempts from least to most destructive (ported from the proven decoder)."""
    from PIL import ImageEnhance, ImageOps

    rgb = image.convert("RGB")
    gray = ImageOps.grayscale(rgb)
    width, height = rgb.size
    return [
        ("original", rgb.copy()),
        ("grayscale", gray.copy()),
        ("contrast-1.8", ImageEnhance.Contrast(gray.copy()).enhance(1.8)),
        ("contrast-2.5", ImageEnhance.Contrast(gray.copy()).enhance(2.5)),
        ("upscale-150", rgb.resize((round(width * 1.5), round(height * 1.5)))),
        ("upscale-2x", rgb.resize((width * 2, height * 2))),
        (
            "upscale-3x-gray-contrast",
            ImageEnhance.Contrast(
                ImageOps.grayscale(rgb.resize((width * 3, height * 3)))
            ).enhance(2.0),
        ),
        ("topcrop-40", rgb.crop((0, 0, width, round(height * 0.40)))),
        ("middlecrop-70", rgb.crop((0, round(height * 0.15), width, round(height * 0.85)))),
        ("rotate90", rgb.rotate(90, expand=True)),
        ("rotate270", rgb.rotate(270, expand=True)),
    ]


def _load_image(data: bytes) -> Any:
    from PIL import Image, UnidentifiedImageError

    try:
        image = Image.open(io.BytesIO(data))
        image.load()
        return image
    except (UnidentifiedImageError, OSError, ValueError) as exc:
        raise DiscDecodeError(
            DiscErrorKind.IMAGE_UNREADABLE,
            "That file is not a readable image. Try a JPEG or PNG photo of the disc.",
            detail=str(exc),
        ) from exc


def decode_disc_image(
    data: bytes,
    *,
    engines: Sequence[str] | None = None,
    variants: Iterable[tuple[str, Any]] | None = None,
) -> list[str]:
    """Decode the PDF417 barcode(s) on a licence-disc photo.

    Returns the raw payload strings (usually one). Raises :class:`DiscDecodeError` with
    ``kind == DiscErrorKind.NO_BARCODE`` when no engine finds a barcode in any variant — the UI
    must show a *different* message for that than for a payload that decoded but held no fields
    (:func:`decode_and_parse` raises ``UNPARSEABLE`` for the latter).
    """
    image = _load_image(data)
    engine_names = tuple(engines) if engines else DEFAULT_ENGINE_ORDER
    attempted: list[str] = []

    for engine_name in engine_names:
        engine = _ENGINES.get(engine_name)
        if engine is None:
            attempted.append(f"{engine_name}: unknown engine")
            continue
        candidates = list(variants) if variants is not None else image_variants(image)
        for variant_name, variant_image in candidates:
            try:
                payloads = engine(variant_image)
            except ImportError as exc:
                attempted.append(f"{engine_name}: not installed ({exc})")
                break
            except Exception as exc:  # noqa: BLE001 - a bad variant must not kill the scan
                attempted.append(f"{engine_name}/{variant_name}: {type(exc).__name__}: {exc}")
                continue
            found = [payload for payload in payloads if payload and payload.strip()]
            if found:
                return _dedupe(found)

    raise DiscDecodeError(
        DiscErrorKind.NO_BARCODE,
        "No barcode found on that photo. Move closer, keep the disc flat and avoid glare — "
        "or paste the barcode text / type the details in.",
        detail="; ".join(attempted[-4:]) if attempted else "no engines available",
    )


def decode_payloads(payloads: Sequence[str]) -> dict[str, Any]:
    """Parse already-decoded payloads, preferring the most confident result."""
    best: dict[str, Any] | None = None
    for payload in payloads:
        parsed = parse_disc_text(payload)
        if not is_disc_parseable(parsed):
            continue
        if parsed["confidence"] == "high":
            return parsed
        if best is None:
            best = parsed
    if best is None:
        raise DiscDecodeError(
            DiscErrorKind.UNPARSEABLE,
            "The barcode was read, but no licence-disc details could be recognised in it.",
            detail=f"{len(payloads)} payload(s) tried",
        )
    return best


def decode_and_parse(data: bytes, *, engines: Sequence[str] | None = None) -> dict[str, Any]:
    """Image bytes -> parsed disc fields, with the two failure kinds kept distinct."""
    payloads = decode_disc_image(data, engines=engines)
    return decode_payloads(payloads)


def _dedupe(values: Iterable[str]) -> list[str]:
    seen: set[str] = set()
    out: list[str] = []
    for value in values:
        if value not in seen:
            seen.add(value)
            out.append(value)
    return out
