"""Programme phase 1 (A1) — NaTIS licence-disc parser port + decode spike.

Two layers of proof:

* **Parity** — ``tests/fixtures/disc/expected_ts.json`` is generated by running the *real,
  already-shipping* TrailerPro parser (``/mnt/d/Claude/trailer-rental-app/src/lib/saDiscParser.ts``)
  over the same payloads via ``scripts/disc_parity_ts.mts``. Every shared field must match
  exactly, so the port is verified against the reference implementation rather than approximated.
* **Behaviour** — the shapes the disc is actually known to use (label-value, percent-delimited,
  pipe/semicolon, space-separated "fixed-width", junk), plus the engine layer's two distinct
  failure kinds.

Note on dates: the reference only accepts a date whose year is within now-5..now+15, so the
fixtures use a 2027 expiry. That stays plausible until 2042, after which the fixtures need
bumping — the same time bomb the reference has.
"""

from __future__ import annotations

import io
import json
import re
from pathlib import Path

import pytest

from app.services import vehicle_disk as vd

FIXTURE_DIR = Path(__file__).resolve().parent / "fixtures" / "disc"
EXPECTED_TS = FIXTURE_DIR / "expected_ts.json"

#: reference key -> our key (the two mass fields are documented string -> float conversions)
SHARED_KEYS = {
    "licenceNumber": "licence_number",
    "make": "make",
    "model": "model",
    "vin": "vin",
    "engineNumber": "engine_number",
    "expiryDate": "expiry_date",
    "colour": "colour",
    "vehicleType": "vehicle_type",
    "confidence": "confidence",
    "rawText": "raw_text",
}

PLATE = "ABC 123 GP"
VIN = "AHTFR22G10L123456"
ENGINE = "2GD1234567"


def load_text(expected_key: str) -> str:
    return (FIXTURE_DIR / f"{expected_key}.txt").read_text(encoding="utf-8")


def load_expected() -> dict:
    return json.loads(EXPECTED_TS.read_text(encoding="utf-8"))


def mass_to_float(value: str) -> float | None:
    return float(value) if str(value).strip() else None


# ── Parity with the real TypeScript parser ──────────────────────────────────


def test_reference_fixtures_exist():
    assert EXPECTED_TS.exists(), "run scripts/disc_parity_ts.mts to regenerate expected_ts.json"
    expected = load_expected()
    assert set(expected) == {
        path.stem for path in FIXTURE_DIR.glob("*.txt")
    }, "expected_ts.json is stale — regenerate it"


@pytest.mark.parametrize(
    "fixture_name", ["labelvalue", "percent", "pipesemi", "fixedwidth", "junk"]
)
def test_port_matches_reference_parser(fixture_name: str):
    expected = load_expected()[fixture_name]
    parsed = vd.parse_disc_text(load_text(fixture_name))

    for ts_key, our_key in SHARED_KEYS.items():
        assert parsed[our_key] == expected[ts_key], (
            f"{fixture_name}: {ts_key} -> {our_key} diverged from saDiscParser.ts"
        )

    # tare/gvm are the only intentional type change: reference strings -> float | None
    assert parsed["tare_kg"] == mass_to_float(expected["tare"])
    assert parsed["gvm_kg"] == mass_to_float(expected["grossMass"])


def test_port_adds_the_fields_the_reference_parses_but_never_exposes():
    parsed = vd.parse_disc_text(load_text("labelvalue"))
    assert parsed["registering_authority"] == "GAUTENG"
    assert parsed["control_number"] == "12345678"
    assert parsed["registration_number"] == "T9876543210"


# ── Label-value shape ───────────────────────────────────────────────────────


def test_label_value_payload_round_trips_into_expected_fields():
    parsed = vd.parse_disc_text(load_text("labelvalue"))

    assert parsed["licence_number"] == PLATE
    assert parsed["make"] == "TOYOTA"
    assert parsed["model"] == "HILUX 2.4 GD-6"
    assert parsed["colour"] == "WHITE"
    assert parsed["vin"] == VIN
    assert parsed["engine_number"] == ENGINE
    assert parsed["expiry_date"] == "2027-03-31"
    assert parsed["tare_kg"] == 1890.0
    assert parsed["gvm_kg"] == 2800.0
    assert parsed["vehicle_type"] == "LDV"
    assert parsed["confidence"] == "high"
    assert parsed["raw_text"].startswith("Registering Authority GAUTENG")


def test_disc_never_invents_a_towing_capacity():
    """Master plan D3: the payload has no towing capacity and no GCM on any code path."""
    parsed = vd.parse_disc_text(load_text("labelvalue"))
    for key in ("towing_capacity_kg", "towing_capacity", "gcm_kg", "gcm"):
        assert key not in parsed
    assert "TOWING" not in parsed["raw_text"].upper().replace("TOWING CAPACITY", "")


# ── The other shapes ────────────────────────────────────────────────────────


def test_percent_delimited_payload():
    parsed = vd.parse_disc_text(load_text("percent"))
    assert parsed["licence_number"] == PLATE
    assert parsed["make"] == "TOYOTA"
    assert parsed["colour"] == "WHITE"
    assert parsed["vin"] == VIN
    assert parsed["expiry_date"] == "2027-03-31"
    assert parsed["tare_kg"] == 1890.0
    assert parsed["gvm_kg"] == 2800.0
    assert parsed["confidence"] == "high"


def test_percent_delimited_engine_number_quirk_is_carried_over_faithfully():
    """Documented reference behaviour, not an ABI bug: in a percent payload the NaTIS
    registration number matches the generic engine-number shape and wins because it appears
    first. Reproduced deliberately so the port stays a port — the scan screen shows raw text
    and unparsed tokens so staff can correct it. See docs/plans/disc-decode-findings.md.
    """
    parsed = vd.parse_disc_text(load_text("percent"))
    assert parsed["engine_number"] == "T9876543210"
    assert parsed["engine_number"] != ENGINE  # the real engine number is in the payload


def test_pipe_and_semicolon_payload():
    parsed = vd.parse_disc_text(load_text("pipesemi"))
    assert parsed["licence_number"] == PLATE
    assert parsed["make"] == "TOYOTA"
    assert parsed["model"] == "HILUX"
    assert parsed["engine_number"] == ENGINE  # token pass gets this one right
    assert parsed["expiry_date"] == "2027-03-31"
    assert parsed["tare_kg"] == 1890.0
    assert parsed["gvm_kg"] == 2800.0
    assert parsed["vehicle_type"] == "LDV"


def test_space_separated_fixed_width_payload_yields_what_the_reference_yields():
    """Measured reference behaviour: the third documented layout ("fixed-width positional") has
    no positional parser. Spaces are not separators, so the line is one token and only the
    top-level regexes fire. ABI carries this over unchanged; the type-the-fields fallback
    covers it, and the gap is flagged for Don in the ledger.
    """
    parsed = vd.parse_disc_text(load_text("fixedwidth"))
    assert parsed["licence_number"] == "ABC123GP"
    assert parsed["vin"] == VIN
    assert parsed["engine_number"] == ENGINE
    assert parsed["vehicle_type"] == "LDV"
    assert parsed["make"] == ""
    assert parsed["model"] == ""
    assert parsed["colour"] == ""
    assert parsed["expiry_date"] == ""
    assert parsed["tare_kg"] is None
    assert parsed["gvm_kg"] is None
    assert parsed["confidence"] == "low"


# ── Junk / robustness ───────────────────────────────────────────────────────


def test_junk_payload_is_low_confidence_empty_but_does_not_crash():
    parsed = vd.parse_disc_text(load_text("junk"))
    assert parsed["confidence"] == "low"
    for key in vd.DISC_FIELD_KEYS:
        assert parsed[key] in ("", None), f"{key} should be empty for junk"
    assert parsed["raw_text"].strip() == load_text("junk").strip()
    assert parsed["unparsed_fields"]


def test_empty_and_whitespace_payloads_do_not_crash():
    for payload in ("", "   ", "\n\n", "%", "|"):
        parsed = vd.parse_disc_text(payload)
        assert parsed["confidence"] == "low"
        assert not vd.is_disc_parseable(parsed)


def test_unparsed_fields_lists_tokens_the_parser_could_not_place():
    parsed = vd.parse_disc_text("Make TOYOTA\n!!weird!!\nGVM 2800")
    assert "!!weird!!" in parsed["unparsed_fields"]
    assert parsed["make"] == "TOYOTA"
    assert parsed["gvm_kg"] == 2800.0


def test_a_fully_structured_label_payload_leaves_nothing_unparsed():
    assert vd.parse_disc_text(load_text("labelvalue"))["unparsed_fields"] == {}


def test_is_disc_parseable_reports_whether_anything_real_came_out():
    assert vd.is_disc_parseable(vd.parse_disc_text(load_text("labelvalue")))
    assert not vd.is_disc_parseable(vd.parse_disc_text(load_text("junk")))


# ── Dates and masses ────────────────────────────────────────────────────────


@pytest.mark.parametrize(
    "raw,expected",
    [
        ("20270331", "2027-03-31"),
        ("2027-03-31", "2027-03-31"),
        ("2027/03/31", "2027-03-31"),
        ("2027.03.31", "2027-03-31"),
        ("31/03/2027", "2027-03-31"),
        ("31-03-2027", "2027-03-31"),
        ("not a date", ""),
        ("", ""),
    ],
)
def test_normalise_date(raw: str, expected: str):
    assert vd.normalise_date(raw) == expected


def test_implausible_dates_are_rejected():
    assert vd.is_plausible_date("2027-03-31", now_year=2026)
    assert not vd.is_plausible_date("1899-03-31", now_year=2026)
    assert not vd.is_plausible_date("2999-03-31", now_year=2026)
    assert not vd.is_plausible_date("2027-13-31", now_year=2026)
    assert not vd.is_plausible_date("")


def test_expiry_date_picks_the_latest_date_when_issue_and_expiry_are_both_present():
    parsed = vd.parse_disc_text("VIN AHTFR22G10L123456\nDate of issue 20240101\nExpiry date 20270331")
    assert parsed["expiry_date"] == "2027-03-31"


def test_masses_are_never_defaulted_to_zero():
    parsed = vd.parse_disc_text("Make TOYOTA\nVIN AHTFR22G10L123456")
    assert parsed["tare_kg"] is None
    assert parsed["gvm_kg"] is None


def test_masses_outside_the_valid_range_are_ignored():
    parsed = vd.parse_disc_text("Tare 12\nGVM 1234567")
    assert parsed["tare_kg"] is None
    assert parsed["gvm_kg"] is None


def test_label_value_mass_range_guard_is_deliberately_stricter_than_the_reference():
    """The reference's label-value mass regex takes the first 3-5 digits and range-checks
    nothing, so "GVM 1234567" becomes 12345 in the reference. D3 says never invent a figure,
    so ABI blanks anything outside 300-80000 kg. The guard can only blank a value, never
    create one — the boundary values themselves still come through."""
    assert vd.parse_disc_text("GVM 1234567")["gvm_kg"] is None
    assert vd.parse_disc_text("GVM 99999")["gvm_kg"] is None
    assert vd.parse_disc_text("Tare 299")["tare_kg"] is None
    assert vd.parse_disc_text("Tare 300")["tare_kg"] == 300.0
    assert vd.parse_disc_text("GVM 80000")["gvm_kg"] == 80000.0


def test_confidence_is_high_only_with_vin_plate_and_make_or_expiry():
    parsed = vd.parse_disc_text("Licence number ABC 123 GP")
    assert parsed["licence_number"] == PLATE
    assert parsed["confidence"] == "low"


# ── Engine layer ────────────────────────────────────────────────────────────


def test_decode_disc_image_rejects_non_image_bytes():
    with pytest.raises(vd.DiscDecodeError) as excinfo:
        vd.decode_disc_image(b"this is definitely not an image")
    assert excinfo.value.kind == vd.DiscErrorKind.IMAGE_UNREADABLE


def test_decode_disc_image_reports_no_barcode_on_a_blank_photo():
    from PIL import Image

    buffer = io.BytesIO()
    Image.new("RGB", (400, 300), "white").save(buffer, format="PNG")
    with pytest.raises(vd.DiscDecodeError) as excinfo:
        vd.decode_disc_image(buffer.getvalue())
    assert excinfo.value.kind == vd.DiscErrorKind.NO_BARCODE


def test_unknown_engine_names_are_skipped_not_fatal():
    from PIL import Image

    buffer = io.BytesIO()
    Image.new("RGB", (80, 60), "white").save(buffer, format="PNG")
    with pytest.raises(vd.DiscDecodeError) as excinfo:
        vd.decode_disc_image(buffer.getvalue(), engines=("no-such-engine",))
    assert excinfo.value.kind == vd.DiscErrorKind.NO_BARCODE
    assert "unknown engine" in excinfo.value.detail


def test_variant_ladder_covers_the_plan_minimum():
    for name in (
        "original",
        "grayscale",
        "contrast-1.8",
        "upscale-2x",
        "topcrop-40",
        "rotate90",
    ):
        assert name in vd.VARIANT_NAMES


def _synthetic_disc_png(payload: str) -> bytes:
    """A real PDF417 of *our* payload, generated locally.

    This is explicitly NOT a fake disc photo: it proves the image -> payload -> fields path
    end-to-end while no genuine disc photograph exists on this machine (see the findings doc).
    """
    zxingcpp = pytest.importorskip("zxingcpp")
    from PIL import Image

    barcode = zxingcpp.create_barcode(payload, zxingcpp.BarcodeFormat.PDF417)
    zxing_image = zxingcpp.write_barcode_to_image(barcode)
    height, width = zxing_image.shape
    pil = Image.frombuffer("L", (width, height), zxing_image, "raw", "L", 0, 1)
    buffer = io.BytesIO()
    pil.convert("RGB").resize((width * 2, height * 2)).save(buffer, format="PNG")
    return buffer.getvalue()


def test_synthetic_barcode_round_trips_through_decode_and_parse():
    payload = load_text("labelvalue")
    image = _synthetic_disc_png(payload)

    payloads = vd.decode_disc_image(image, engines=("zxing-cpp",))
    assert len(payloads) >= 1
    assert payloads[0] == payload

    parsed = vd.decode_and_parse(image, engines=("zxing-cpp",))
    assert parsed["licence_number"] == PLATE
    assert parsed["vin"] == VIN
    assert parsed["make"] == "TOYOTA"
    assert parsed["tare_kg"] == 1890.0
    assert parsed["gvm_kg"] == 2800.0
    assert parsed["confidence"] == "high"


def test_default_engine_order_also_reads_a_real_barcode():
    """The measured default order must actually work on a real PDF417 image."""
    image = _synthetic_disc_png(load_text("labelvalue"))
    parsed = vd.decode_and_parse(image)
    assert parsed["licence_number"] == PLATE


def test_decoded_but_fieldless_payload_raises_unparseable_not_no_barcode():
    """The UI has to tell "no barcode on the photo" apart from "barcode found, nothing in it"."""
    image = _synthetic_disc_png("THIS IS NOT A LICENCE DISC - please rescan @@##$$")
    with pytest.raises(vd.DiscDecodeError) as excinfo:
        vd.decode_and_parse(image, engines=("zxing-cpp",))
    assert excinfo.value.kind == vd.DiscErrorKind.UNPARSEABLE


def test_decode_payloads_prefers_the_high_confidence_payload():
    junk = load_text("junk")
    good = load_text("labelvalue")
    parsed = vd.decode_payloads([junk, good])
    assert parsed["confidence"] == "high"
    assert parsed["licence_number"] == PLATE


def test_decode_payloads_raises_when_nothing_is_parseable():
    with pytest.raises(vd.DiscDecodeError) as excinfo:
        vd.decode_payloads([load_text("junk")])
    assert excinfo.value.kind == vd.DiscErrorKind.UNPARSEABLE


# ── The real modern disc layout (positional) ────────────────────────────────


def test_positional_layout_is_detected_by_its_own_length_self_check():
    raw = load_text("natis_positional").strip()
    parsed = vd.parse_natis_positional(raw)
    assert parsed is not None
    # field 2 is the record's own length, zero-padded to four digits ("0148" == 148 chars)
    assert raw.split("%")[2] == "0148"
    assert int(raw.split("%")[2]) == len(raw)


def test_positional_layout_places_every_unambiguous_field():
    parsed = vd.parse_disc_text(load_text("natis_positional"))
    assert parsed["make"] == "MITSUBISHI"
    assert parsed["model"] == "ASX"
    assert parsed["colour"] == "WHITE"          # "White / Wit" -> EN half
    assert parsed["vin"] == "AHTFR22G10L123456"
    assert parsed["engine_number"] == "2GD1234567"   # NOT the MVL1CC53 form identifier
    assert parsed["expiry_date"] == "2027-07-31"
    assert parsed["vehicle_type"] == "STATION WAGON"  # "Station wagon / Stasiewa" -> EN half
    assert parsed["tare_kg"] is None
    assert parsed["gvm_kg"] is None
    assert parsed["confidence"] == "high"


def test_positional_layout_refuses_a_payload_whose_length_self_check_fails():
    raw = load_text("natis_positional").strip().replace("%0148%", "%0149%", 1)
    assert vd.parse_natis_positional(raw) is None


def test_positional_layout_refuses_a_payload_without_a_valid_vin():
    raw = load_text("natis_positional").strip().replace("AHTFR22G10L123456", "NOTAVIN", 1)
    assert vd.parse_natis_positional(raw) is None


def test_positional_identifiers_are_flagged_rather_than_guessed():
    """Which of the disc's identifier fields is the NaTIS registration number and which the
    licence number is not confirmed yet (needs a full printed disc face), so D3 says: show them
    for the staff member to place, never guess. The one the plate regex did match is kept as the
    licence number; the others are surfaced with the reason."""
    parsed = vd.parse_disc_text(load_text("natis_positional"))
    assert parsed["licence_number"] == "ABC123GP"
    flagged = {key: value for key, value in parsed["unparsed_fields"].items() if "identifier" in value}
    assert "T9876543210X" in flagged
    assert "ZZ1234Z" in flagged
    assert "ABC123GP" not in flagged  # it is the plate we kept


def test_positional_result_deliberately_differs_from_the_reference_sniffer():
    """The reference's percent branch is a token sniffer. On the real modern payload it puts the
    form identifier MVL1CC53 in engine_number and leaves colour empty — measured, and recorded
    here so the divergence from saDiscParser.ts is visible and deliberate, not drift."""
    reference = load_expected()["natis_positional"]
    ours = vd.parse_disc_text(load_text("natis_positional"))
    assert reference["engineNumber"] == "MVL1CC53"
    assert reference["colour"] == ""
    assert ours["engine_number"] == "2GD1234567"
    assert ours["colour"] == "WHITE"


# ── The real disc photograph (never committed — skips when absent) ──────────

REAL_DISC_SAMPLE = Path.home() / "disc-samples" / "disc-2026-09-23.jpg"


@pytest.mark.skipif(not REAL_DISC_SAMPLE.exists(), reason="no real disc photo in ~/disc-samples/")
def test_real_disc_photo_decodes_and_parses_end_to_end():
    """The end-to-end proof on real input: photograph -> barcode -> 148-char payload -> fields.

    The photo is Don's and stays out of git (it carries a real plate/VIN/engine number), so this
    test skips cleanly on any machine that does not have it.
    """
    parsed = vd.decode_and_parse(REAL_DISC_SAMPLE.read_bytes())

    assert parsed["confidence"] == "high"
    assert parsed["make"] == "MITSUBISHI"
    assert parsed["model"] == "ASX"
    assert parsed["colour"] == "WHITE"
    assert parsed["vehicle_type"] == "STATION WAGON"
    assert re.fullmatch(r"[A-HJ-NPR-Z0-9]{17}", parsed["vin"])
    assert re.fullmatch(r"\d{4}-\d{2}-\d{2}", parsed["expiry_date"])
    assert parsed["engine_number"] != "MVL1CC53"  # the form identifier must not land in engine no.
    assert parsed["tare_kg"] is None
    assert parsed["gvm_kg"] is None
    assert "%MVL" in parsed["raw_text"]
    # the record's own length self-check holds on the real payload
    assert int(parsed["raw_text"].strip().split("%")[2]) == len(parsed["raw_text"].strip())


@pytest.mark.skipif(not REAL_DISC_SAMPLE.exists(), reason="no real disc photo in ~/disc-samples/")
def test_real_disc_photo_is_read_by_the_default_engine_at_the_original_size():
    """D2 settled by measurement: the real photo decodes on the ORIGINAL variant, so no crop or
    upscale is needed for it."""
    payloads = vd.decode_disc_image(REAL_DISC_SAMPLE.read_bytes(), engines=("zxing-cpp",))
    assert len(payloads) == 1
    assert payloads[0].startswith("%MVL")


def test_field_labels_cover_every_parseable_field():
    assert set(vd.FIELD_LABELS) == set(vd.DISC_FIELD_KEYS)


def test_module_does_not_import_the_engines_at_import_time():
    """A missing engine must not stop the app booting — the imports are lazy."""
    source = Path(vd.__file__).read_text(encoding="utf-8")
    top_level = [
        line
        for line in source.splitlines()
        if re.match(r"^(import|from)\s+(zxingcpp|pdf417decoder)", line)
    ]
    assert top_level == [], f"engine imported at module scope: {top_level}"
